name: Publish Python package

on:
  push:
    branches:
      - main  # Ubah dengan nama branch Anda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Versi Python yang Anda gunakan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build the package
        run: python setup.py sdist bdist_wheel
      - name: Publish the package to PyPI
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__  # Ini adalah username untuk token
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Token yang disimpan di GitHub Secrets
          
